FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN python -c "from faster_whisper import WhisperModel; WhisperModel('small', device='cpu', compute_type='int8')"
RUN apt-get update && apt-get install -y --no-cache pango cairo gdk-pixbuf
RUN pip install -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]