services:
  backend:
    build:
      context: ./cognora-backend
    ports:
      - "8000:8000"
    env_file:
      - ./cognora-backend/.env
    depends_on:
      - redis

  worker:
    build:
      context: ./cognora-backend
    command: python -m workers.worker
    depends_on:
      - redis
    env_file:
      - ./cognora-backend/.env

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./cognora-frontend
      args:
        - DATABASE_URL=${DATABASE_URL}
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        - NEXT_PUBLIC_CLERK_SIGN_IN_URL=${NEXT_PUBLIC_CLERK_SIGN_IN_URL}
        - NEXT_PUBLIC_CLERK_SIGN_UP_URL=${NEXT_PUBLIC_CLERK_SIGN_UP_URL}
        - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=${NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL}
        - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=${NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL}
    ports:
      - "3000:3000"
    env_file:
      - ./cognora-frontend/.env